### ISSUE TITLE
Why use multiple sigmoids for relation classifier?

### ISSUE THREAD

**Issue by syuoni** [lavis-nlp/spert#47]
Hi, 
May I ask why you use multiple sigmoids for relation classifier? Why not use a softmax layer as for the span classifier?

I have checked that there are no multiple relations between two given entities in all three datasets (only a very few duplicated relations in SciERC). 

Best,
Enwei

**Comment by markus-eberts** [comment]
Hi,
this question was already answered in issue #10.
