### ISSUE TITLE
Can't make predictions following the example

### ISSUE THREAD

**Issue by xegulon** [lavis-nlp/spert#52]
I'm, thanks for the code

I've tried to run the predictions mode following this: https://github.com/lavis-nlp/spert#examples.

I have downloaded the spacy model, but I get the following error:

```bash
OSError: Can't load tokenizer for 'data/models/conll04'. Make sure that: ...
```

How can I solve it?

**Comment by markus-eberts** [comment]
Did you fetch the datasets and models first? There should be a conll04 model under /data/models.
If not, try this:
bash ./scripts/fetch_datasets.sh
bash ./scripts/fetch_models.sh

**Comment by xegulon** [comment]
Yeah I've already done this, it seems it worked:

![image](https://user-images.githubusercontent.com/74178038/121523409-78c13d80-c9f6-11eb-9929-95af29ac24f7.png)

**Comment by markus-eberts** [comment]
It works for me. Did you navigate into the root SpERT folder (with the spert.py file) and executed 'python ./spert.py predict --config configs/example_predict.conf'? Which transformers version are you using?

**Comment by xegulon** [comment]
Finally it works. My mistake was that I ran the script from elsewhere than the root folder. Thanks!

**Comment by xegulon** [comment]
However, I can't make predictions with raw `.txt` files. I get a JSON error.

**Comment by markus-eberts** [comment]
Yes, the code currently supports only JSON input files in one of the three formats shown in 'conll04_prediction_example.json'

**Comment by markus-eberts** [comment]
For example, you can convert sentences in your .txt file into the following format and save it as a JSON file:
[ "In 1822, the 18th president of the United States, Ulysses S. Grant, was born in Point Pleasant, Ohio.", "Sentence 2", ...]

**Comment by xegulon** [comment]
Ow I see thanks a lot! What about using it for inference like what I asked there https://github.com/lavis-nlp/spert/issues/51 ?
